routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*CAMBIAR MAIN POR HOME, para que se vea "mejor"*/
Route::get('/', function () {
    if(Auth::check()){
		return view('/main'); //cambia main por welcome para ver lo de login
	}else{
		return view('auth/login');
	}
});

/*
Route::get('/master', function () {//esto hay que cambiarlo
	if(Auth::check()){
		return view('/main');
	}else{
		return view('auth/login');
	}
    
});
*/
Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/main', 'HomeController@index');

//usuarios
Route::resource('/usuarios','UsersController');
Route::get('/usuarios/delete/{id?}','UsersController@delete');



//pacientes
Route::resource('/pacientes','PacientesController');
Route::get('/pacientes/delete/{id?}','PacientesController@delete');

//enfermedades
Route::resource('/enfermedades','EnfermedadesController');
Route::get('/enfermedades/delete/{id?}','EnfermedadesController@delete');

app/Paciente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Paciente extends Model
{
    use SoftDeletes;

    protected $table = "pacientes";
    //public $timestamps = true;
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nombre', 'correo', 'apellido',
    ];
    
}

app/Http/Controllers/PacientesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth; /*para poder usar el Auth:: ...*/

use Validator;
use DB;

use App\Paciente as Paciente;
use App\Enfermedad as Enfermedad;
use App\EnfermedadesFicha as EnfermedadesFicha;
use App\Ficha as Ficha;
use App\User as User;

class PacientesController extends Controller
{

    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pacientes = Paciente::all();

        return view('pacientes.index')->with('pacientes',$pacientes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::user()->can('crear_pacientes')){
            $enfermedades = Enfermedad::all();
            return view('pacientes.add')->with('enfermedades',$enfermedades);
        }else{
            return redirect()->back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        //dd($request->all());
        //mensajes de los validadores
        $messages = [
            'required'    => 'Debe ingresar el  :attribute',
            'correo.required'    => 'Debe ingresar el  correo',
            'numeric' => 'El :attribute debe solo contener números',
            'unique' => '¡El :attribute ya existe!',
            'max' => 'El :attribute no debe exeder los :max caracteres',
            'min' => 'El :attribute debe tener minimo :min caracteres',
            'confirmed' => 'Debe ingresar las 2 contraseñas iguales',
            'email' => 'Debe ingresar un correo valido',
            'cl_rut' =>'Debe ingresar un rut valido',
            'date' => ':attribute no es una fecha válida,ingrese una fecha válida.',
        ];
        //validador de los input del formulario
        $validator = Validator::make($request->all(), [
                'nombre'  => 'required|max:100',
                'apellido' => 'required|max:100',
                'rut'   => 'required|cl_rut',
                'edad' => 'required|numeric',
                'fecha_nacimiento' => 'required|date',
                'prevision' => 'required|',
                'correo' => 'required|email|unique:pacientes,correo|max:255',
                'telefono_contacto' => 'numeric',
                'direccion' => 'required',
            ], $messages);

        //Si contiene errores se devuelve al formulario con todos los errores, de lo contrario guarda en la base de datos
        if ($validator->fails()) {
            return redirect()->back()->withInput($request->all())->withErrors($validator);
        }else{
            $paciente = new Paciente();
            $paciente->nombre = formato_guarda_input($request->input("nombre"));
            $paciente->apellido = formato_guarda_input($request->input("apellido"));
            $paciente->correo = formato_guarda_input($request->input("correo"));
            if($request->input("telefono_contacto") != ""){
                $paciente->telefono_contacto = $request->input("telefono_contacto");
            }else{
                $paciente->telefono_contacto = NULL;
            }
            
            $paciente->edad = $request->input("edad");
            $paciente->fecha_nacimiento = formato_fecha($request->input("fecha_nacimiento"));
            $paciente->direccion = formato_guarda_input($request->input("direccion"));
            $paciente->prevision = formato_guarda_input($request->input("prevision"));
            $paciente->rut = formato_guarda_rut($request->input("rut"));
            /*FILTRO PARA QUE NO SE DUPLIQUEN LOS RUT*/
            $contador= DB::table('pacientes')->where('rut','=', $paciente->rut)->count();
            if($contador != 0){
                return redirect()->back()->withInput($request->all())->with('success', 'errorRut');
            }
            /*FIN FILTRO PARA QUE NO SE DUPLIQUEN LOS RUT*/
           
            
            $paciente->config = 1;
            $paciente->save();
            //crear ficha
            $nuevaFicha = new Ficha();
            $nuevaFicha->id_paciente = $paciente->id;
            $nuevaFicha->id_creador = Auth::user()->id;
            $nuevaFicha->motivo = formato_guarda_input($request->input("motivo"));
            $nuevaFicha->save();
            //crear enfermedadesFicha
            foreach ($request->input("enf") as $key => $enfermedad) {//$enfermedad tiene el id de las enfermedades seleccionadas
                //$aux =$aux."+".$enfermedad."+";
                $nuevaEnfermedadesFicha = new EnfermedadesFicha();
                $nuevaEnfermedadesFicha->id_ficha = $nuevaFicha->id;
                $nuevaEnfermedadesFicha->id_enfermedad = $enfermedad;
                $nuevaEnfermedadesFicha->save();
            }

            
        }

        return redirect("pacientes")->with('success', 'add')->with("id_paciente", $paciente->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(Auth::user()->can('ver_pacientes')){
            $paciente = Paciente::findorfail($id);
            //obtener la edad del paciente
            $datetime1 = date_create($paciente->fecha_nacimiento);
            $datetime2 = date_create(date("d-m-Y"));
            $interval = date_diff($datetime1, $datetime2);
            //$añosDiferencia = $interval->y;
            $edadPaciente = $interval->y;
            return view('pacientes.modalver')->with('paciente',$paciente)->with('edadPaciente',$edadPaciente);
        }else{
            return redirect()->back();
        }

        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::user()->can('editar_pacientes')){
            $paciente = Paciente::findorfail($id);
            return view('pacientes.edit')->with('paciente',$paciente);
        }else{
            return redirect()->back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //dd($request->all());
        $paciente = Paciente::findorfail($id);
        //mensajes de los validadores
        $messages = [
            'required'    => 'Debe ingresar el  :attribute',
            'correo.required'    => 'Debe ingresar el  correo',
            'numeric' => 'El :attribute debe solo contener números',
            'unique' => '¡El :attribute ya existe!',
            'max' => 'El :attribute no debe exeder los :max caracteres',
            'min' => 'El :attribute debe tener minimo :min caracteres',
            'confirmed' => 'Debe ingresar las 2 contraseñas iguales',
            'email' => 'Debe ingresar un correo valido',
            'cl_rut' =>'Debe ingresar un rut valido',
            'date' => ':attribute no es una fecha válida,ingrese una fecha válida.',
        ];

        if($paciente->correo == formato_guarda_input($request->input("correo"))){//no se cambia correo
            $validator = Validator::make($request->all(), [
                    'nombre'  => 'required|max:100',
                    'apellido' => 'required|max:100',
                    'rut'   => 'required|cl_rut',
                    'edad' => 'required|numeric',
                    'fecha_nacimiento' => 'required|date',
                    'prevision' => 'required|',
                    'correo' => 'required|email|max:255',
                    'telefono_contacto' => 'numeric',
                    'direccion' => 'required',
                ], $messages);
        }else{//se cambia correo
            //validador de los input del formulario
            $validator = Validator::make($request->all(), [
                    'nombre'  => 'required|max:100',
                    'apellido' => 'required|max:100',
                    'rut'   => 'required|cl_rut',
                    'edad' => 'required|numeric',
                    'fecha_nacimiento' => 'required|date',
                    'prevision' => 'required|',
                    'correo' => 'required|email|unique:pacientes,correo|max:255',
                    'telefono_contacto' => 'numeric',
                    'direccion' => 'required',
                ], $messages);
        }
        

        //Si contiene errores se devuelve al formulario con todos los errores, de lo contrario guarda en la base de datos
        if ($validator->fails()) {
            return redirect()->back()->withInput($request->all())->withErrors($validator);
        }else{
            $paciente->nombre = formato_guarda_input($request->input("nombre"));
            $paciente->apellido = formato_guarda_input($request->input("apellido"));
            $paciente->correo = formato_guarda_input($request->input("correo"));
            if($request->input("telefono_contacto") != ""){
                $paciente->telefono_contacto = $request->input("telefono_contacto");
            }else{
                $paciente->telefono_contacto = NULL;
            }
            
            $paciente->edad = $request->input("edad");
            $paciente->fecha_nacimiento = formato_fecha($request->input("fecha_nacimiento"));
            $paciente->direccion = formato_guarda_input($request->input("direccion"));
            $paciente->prevision = formato_guarda_input($request->input("prevision"));

resources/views/pacientes/index.blade.php
@extends('master')

@section('title', 'Pacientes')

@push('css-head')
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="{{asset('assets/plugins/select2/select2_conquer.css')}}"/>
<link rel="stylesheet" href="{{asset('assets/plugins/data-tables/DT_bootstrap.css')}}"/>
<!-- END PAGE LEVEL STYLES -->

@endpush

@section('content')

<!-- BEGIN CONTENT -->

<div class="page-content-wrapper">
	<div class="page-content-wrapper">
		<div class="page-content">

			<!-- BEGIN PAGE CONTENT-->
			<div class="row">
				<div class="col-md-12">
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div class="portlet">
						<div class="portlet-title">
							<div class="caption">
								<i class="flaticon-015-chair flaticon-med" style="color: black;"></i>Panel de Pacientes
							</div>
							<div class="actions">
								<div class="btn-group">
									<a class="btn btn-info dropdown-toggle" href="#" data-toggle="dropdown">
									Columnas <i class="fa fa-angle-down"></i>
									</a>
									<div id="sample_2_column_toggler" class="dropdown-menu hold-on-click dropdown-checkboxes pull-right">
										<label><input type="checkbox" checked data-column="0">Nombre</label>
										<label><input type="checkbox" checked data-column="1">Correo</label>
										<label><input type="checkbox" checked data-column="2">Rut</label>
										<label><input type="checkbox" checked data-column="3">Teléfono Contacto</label>
										<label><input type="checkbox" checked data-column="4">Acción</label>
									</div>
								</div>
							</div>
						</div>
						<div class="portlet-body">
							@if(session("success"))
								@if(Session::get("success")=="add")
									<div class="alert alert-success alert-dismissable">
										<button type="button" title="Cerrar" class="close" data-dismiss="alert" aria-hidden="true"></button>
										<i class="fa fa-thumbs-up fa-flip-horizontal"></i> <strong>¡Paciente creado correctamente!</strong> Tienes {{count($pacientes)}} pacientes en el sistema. <u><strong><a class="view-data" data-role="{{session('id_paciente')}}" style="cursor: pointer;" >Has click aqui para ver el último paciente que creaste</a></strong></u>
									</div>
								@endif
								@if(Session::get("success")=="edit")
									<div class="alert alert-success alert-dismissable">
										<button type="button" title="Cerrar" class="close" data-dismiss="alert" aria-hidden="true"></button>
										<i class="fa fa-thumbs-up fa-flip-horizontal"></i> <strong>¡Paciente editado correctamente!</strong> Tienes {{count($pacientes)}} pacientes en el sistema. <u><strong><a class="view-data" data-role="{{session('id_paciente')}}" style="cursor: pointer;" >Has click aqui para ver el último paciente que editaste</a></strong></u>
									</div>
								@endif
								@if(Session::get("success")=="delete")
									<div class="alert alert-success alert-dismissable">
										<button type="button" title="Cerrar" class="close" data-dismiss="alert" aria-hidden="true"></button>
										<i class="fa fa-thumbs-up fa-flip-horizontal"></i> <strong>¡Paciente eliminado correctamente!</strong> Tienes {{count($pacientes)}} pacientes en el sistema.
									</div>
								@endif
							@endif
							<div class="table-toolbar">
								<div class="btn-group">
									@permission('crear_pacientes')
									<a id="sample_editable_1_new" title="Agregar Nuevo Paciente" href="pacientes/create" class="btn btn-success">
									Agregar Nuevo Paciente <i class="fa fa-plus"></i>
									@endpermission
									</a>
									
								</div>
							</div>
							<table class="table table-striped table-bordered table-hover table-full-width" id="sample_2">
								<thead>
								<tr>
									<th>Nombre</th>
									<th>Correo</th>
									<th class="hidden-xs">Rut</th>
									<th class="hidden-xs">Teléfono Contacto</th>
									<th class="hidden-xs">Acción</th>
								</tr>
								</thead>
								<tbody>
								@foreach($pacientes as $paciente)
								<tr>
									<td>{{ $paciente->nombre." ".$paciente->apellido }}</td>
									<td>{{ $paciente->correo }}</td>
									<td>{{ formato_rut($paciente->rut) }}</td>
									<td>{{ $paciente->telefono_contacto}}</td>
									<td>
										<!-- div botones-->
										<div class="clearfix">
											<div class="btn-group">
												@permission('ver_pacientes')
												<a class="btn btn-default view-data" title="Ver" data-role="{{$paciente->id}}" ><i class="fa fa-eye"></i></a>
												@endpermission
												@if($paciente->config == 1)
												@permission('editar_pacientes')
												<a href="{{ url("/pacientes/$paciente->id/edit") }}" title="Editar" class="btn btn-default"><i class="fa fa-edit"></i></a>
												@endpermission
												@permission('eliminar_pacientes')
												<a class="btn btn-default delete-data" title="Eliminar" data-role="{{$paciente->id}}" ><i class="fa fa-trash"></i></a>
												@endpermission
												@endif
											</div>
										</div>
										<!-- /div botones -->
									</td>
								</tr>
								@endforeach
								</tbody>
							</table>
						</div>
					</div>
					<!-- END EXAMPLE TABLE PORTLET-->
				</div>
			</div>
			<!-- END PAGE CONTENT-->
			
			
			
			
		</div> <!--/div class="page-content" -->
	</div> <!--/div class="page-content-wrapper" -->
</div><!--/div class="page-content-wrapper" -->
<!-- END CONTENT -->
<div id="modal"></div>
@endsection

@push('script-footer')
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="{{ asset('assets/plugins/select2/select2.min.js') }} "></script>
<script type="text/javascript" src="{{ asset('assets/plugins/data-tables/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/plugins/data-tables/DT_bootstrap.js') }}"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{ asset('assets/scripts/app.js') }} "></script>
<script src="{{ asset('assets/scripts/table-advanced.js') }} "></script>


<script type="text/javascript">
	$(document).ready(function(){
		App.init(); // initlayout and core plugins
		TableAdvanced.init();

   		$("#pacientes").addClass( "active" );
		$("#pacientes-li").addClass( "active" );
		$("#pacientes-a").append( '<span class="selected"></span>' );

		$(".delete-data").click(function(){
		  var data = $(this).data("role");
		  $.get( "pacientes/delete/" + data, function( data ) {
			  $( "#modal" ).html( data );
			  $( "#modalEliminar" ).modal();
			});
		});

		$(".view-data").click(function(){
		  var data = $(this).data("role");
		  $.get( "pacientes/" + data, function( data ) {
			  $( "#modal" ).html( data );
			  $( "#modalVer" ).modal();
			});
		});

	});
</script>

@endpush

resources/views/pacientes/modaldelete.blade.php
<div id="modalEliminar" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-md" >
        <div class="modal-content">
          <div class="modal-header" style="color: red">
           <i class="fa fa-warning"></i> <strong>  ELIMINAR </strong>
          </div>
          <div class="modal-body">
          	<center>
			<p>¿Está seguro que desea eliminar este paciente?</p>
			<p>{{ $paciente->nombre ." ". $paciente->apellido }}</p>
			</center>
			<form action="{{ route('pacientes.destroy',$paciente->id) }}" method="post">
				<div class="modal-footer">
					<input type="hidden" name="_token" value="{{ csrf_token() }}">
					<span>
				    	<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					</span>
					<span>
						<button type="submit" title="Confirmar" class="btn btn-info btn-borrar">Confirmar</a>
					</span>
                	{{ method_field('DELETE') }}
				</div>
			</form>
        	</div>
    	</div>
  	</div><!--/modal dialog-->
</div>

resources/views/pacientes/modalver.blade.php
<div id="modalVer" class="modal fade" tabindex="-1" aria-hidden="false">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header" style="color: rgb(41, 175, 228);">
				<button type="button" title="Cerrar" class="close" data-dismiss="modal" aria-hidden="true"></button>
				<strong>Información del Paciente</strong>
			</div>
			<div class="modal-body">
						<table class="table table-bordered table-hover table-responsive">
						<tbody>
							<tr>
								<th width="25%">Nombre:</th>
								<td width="45%"> {{$paciente->nombre}} {{$paciente->apellido}}</td>
							</tr>
							<tr>
								<th >Correo:</th>
								<td >{{$paciente->correo}}</td>
							</tr>
							<tr>
								<th>Edad:</th>
								<td>{{$edadPaciente}}</td>
							</tr>
							<tr>
								<th>Fecha Nacimiento:</th>
								<td>{{ formato_fecha($paciente->fecha_nacimiento) }}</td>
							</tr>
							<tr>
								<th>Rut:</th>
								<td>{{ formato_rut($paciente->rut) }}</td>
							</tr>
							<tr>
								<th>Teléfono Contacto:</th>
								<td>{{ $paciente->telefono_contacto }}</td>
								
							</tr>
							<tr>
								<th>Dirección :</th>
								<td>{{$paciente->direccion }}</td>
							</tr>
							<tr>
								<th>Previsión:</th>
								<td>{{$paciente->prevision }}</td>
							</tr>
							
						</tbody>
					</table>
					
			</div><!--/modal body-->
			<div class="modal-footer">
				@permission('editar_pacientes')
				<a href="{{ url("/pacientes/$paciente->id/edit") }}" title="Editar" class="btn btn-warning pull-right"><i class="fa fa-edit"></i> Editar</a>
				@endpermission
			</div>
		</div>
	</div>
</div>