routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*CAMBIAR MAIN POR HOME, para que se vea "mejor"*/
Route::get('/', function () {
    if(Auth::check()){
		return view('/main'); //cambia main por welcome para ver lo de login
	}else{
		return view('auth/login');
	}
});

/*
Route::get('/master', function () {//esto hay que cambiarlo
	if(Auth::check()){
		return view('/main');
	}else{
		return view('auth/login');
	}
    
});
*/
Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/main', 'HomeController@index');

//usuarios
Route::resource('/usuarios','UsersController');
Route::get('/usuarios/delete/{id?}','UsersController@delete');



//pacientes
Route::resource('/pacientes','PacientesController');
Route::get('/pacientes/delete/{id?}','PacientesController@delete');

//enfermedades
Route::resource('/enfermedades','EnfermedadesController');
Route::get('/enfermedades/delete/{id?}','EnfermedadesController@delete');

app/Http/Controllers/EnfermedadesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Validator;
use DB;

use App\Enfermedad as Enfermedad;

class EnfermedadesController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $enfermedades = Enfermedad::all();

        return view('enfermedades.index')->with('enfermedades',$enfermedades);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::user()->can('crear_enfermedades')){
            return view('enfermedades.add');
        }else{
            return redirect()->back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //mensajes de los validadores
        $messages = [
            'required'    => 'Debe ingresar el  :attribute',
            'unique' => '¡El :attribute ya existe!',
            'max' => 'El :attribute no debe exeder los :max caracteres',
            'min' => 'El :attribute debe tener minimo :min caracteres',
        ];
        //validador de los input del formulario
        $validator = Validator::make($request->all(), [
                'nombre'  => 'required|max:180',
            ], $messages);

        //Si contiene errores se devuelve al formulario con todos los errores, de lo contrario guarda en la base de datos
        if ($validator->fails()) {
            return redirect()->back()->withInput($request->all())->withErrors($validator);
        }else{
            $enfermedad = new Enfermedad();
            $enfermedad->nombre = formato_guarda_input($request->input("nombre"));
            $enfermedad->config = 1;
            $enfermedad->save();
        }

        return redirect("enfermedades")->with('success', 'add')->with("id_enfermedad", $enfermedad->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(Auth::user()->can('ver_enfermedades')){
            $enfermedad = Enfermedad::findorfail($id);
            return view('enfermedades.modalver')->with('enfermedad',$enfermedad);
        }else{
            return redirect()->back();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::user()->can('editar_enfermedades')){
            $enfermedad = Enfermedad::findorfail($id);
            return view('enfermedades.edit')->with('enfermedad',$enfermedad);
        }else{
            return redirect()->back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //mensajes de los validadores
        $messages = [
            'required'    => 'Debe ingresar el  :attribute',
            'unique' => '¡El :attribute ya existe!',
            'max' => 'El :attribute no debe exeder los :max caracteres',
            'min' => 'El :attribute debe tener minimo :min caracteres',
        ];
        //validador de los input del formulario
        $validator = Validator::make($request->all(), [
                'nombre'  => 'required|max:180',
            ], $messages);

        //Si contiene errores se devuelve al formulario con todos los errores, de lo contrario guarda en la base de datos
        if ($validator->fails()) {
            return redirect()->back()->withInput($request->all())->withErrors($validator);
        }else{
            $enfermedad = Enfermedad::findorfail($id);
            $enfermedad->nombre = formato_guarda_input($request->input("nombre"));
            
            $enfermedad->save();
        }

        return redirect("enfermedades")->with('success', 'edit')->with("id_enfermedad", $enfermedad->id);
    }

    /*para modal que pregunta si quiere borrar*/
    public function delete($id=null)
    {
        if(Auth::user()->can('eliminar_enfermedades')){
            $enfermedad = Enfermedad::findorfail($id);
            if($enfermedad == NULL){
                return redirect('pacientes');
            }else{
                return view('enfermedades.modaldelete')->with('enfermedad',$enfermedad);
            }
        }else{
            return redirect()->back();
        }  
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $enfermedad = Enfermedad::findorfail($id);
        $enfermedad->delete();

        return redirect("enfermedades")->with('success','delete');
    }
}

resources/views/enfermedades/add.blade.php
@extends('master')

@section('title', 'Enfermedades Agregar')

@push('css-head')
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="{{asset('assets/plugins/select2/select2_conquer.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{ asset('assets/plugins/bootstrap-toastr/toastr.min.css') }}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/plugins/bootstrap-datepicker/css/datepicker.css')}}"/>


<!-- END PAGE LEVEL STYLES -->
@endpush

@section('content')

@section('content')

<!-- BEGIN CONTENT -->

<div class="page-content-wrapper">
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN PAGE CONTENT-->
			<div class="row">
				<div class="col-md-12">
					<div class="portlet">
						<div class="portlet-title">
							<div class="caption">
								<i class="flaticon-002-first-aid-kit flaticon-med" style="color: black;"></i>Panel de Enfermedades
							</div>
						</div>
						<div class="portlet-body form">
						@if ($errors->any())
							<div class="note note-danger">
								<h6 class="block"><strong>Sigue las siguientes instrucciones :</strong></h6>
								<ul>
						            @foreach ($errors->all() as $error)
						                <li>{{ $error }}</li>
						            @endforeach
						        </ul>
							</div>
						@endif
						<form method="post" class="horizontal-form" id="form_enfermedades" action="{{url("enfermedades")}}">
							<div class="form-body">
								<h3 class="form-section">Agregar Enfermedad</h3>
								<div class="row">
									<div class="col-md-8">
										<div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
											<label class="control-label">Nombre (*)</label>
											<input type="text" id="nombre" name="nombre" class="form-control mayusculas" value="{{ old('nombre') }}" placeholder="Nombre de la Enfermedad" maxlength="180" required onkeyup="verificarNombre(this.value);">
										</div>
									</div>
								</div><!--/row-->
								
								
								
								
								
							</div><!--/div class="form-body"-->
							<div class="form-actions right">
								<a href="{{ asset('enfermedades') }}" title="Cancelar" class="btn btn-default">Cancelar</a>
								<button type="submit" title="Guardar" class="btn btn-info"><i class="fa fa-check"></i> Guardar</button>
							</div>
							{{ csrf_field() }}
						</form>
						</div>
				</div>
			</div>
			<!-- END PAGE CONTENT-->
			
		</div> <!--/div class="page-content" -->
	</div> <!--/div class="page-content-wrapper" -->
</div><!--/div class="page-content-wrapper" -->
<!-- END CONTENT -->
@endsection

@push('script-footer')
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="{{ asset('assets/plugins/select2/select2.min.js') }} "></script>
<script src="{{ asset('assets/plugins/bootstrap-toastr/toastr.min.js') }}"></script>

<script type="text/javascript" src="{{asset('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js')}}"></script>

<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{ asset('assets/scripts/app.js') }} "></script>
<script src="{{ asset('assets/scripts/ui-toastr.js') }}"></script>



<script type="text/javascript">
	$(document).ready(function(){
		App.init(); // initlayout and core plugins
		

   		$("#enfermedades").addClass( "active" );
		$("#enfermedades-li").addClass( "active" );
		$("#enfermedades-a").append( '<span class="selected"></span>' );
		

		/*
	    $("#fecha_nacimiento").change(function(){
            alert($('#fecha_nacimiento').val());
            //$('#valor2').val($(this).val());
		});
		+/

		/*Con esto no se deja ingresar nada que no sea letras*/
	    $(".letras").keypress(function (key) {
            //window.console.log(key.charCode);//imprime el codigo ascii
            if (
                (key.charCode < 97 || key.charCode > 122)//letras mayusculas
                && (key.charCode < 65 || key.charCode > 90) //letras minusculas
                && (key.charCode != 0) //borrar
                && (key.charCode != 32) //espacio
                && (key.charCode != 241) //ñ
                 && (key.charCode != 209) //Ñ
                 && (key.charCode != 225) //á
                 && (key.charCode != 233) //é
                 && (key.charCode != 237) //í
                 && (key.charCode != 243) //ó
                 && (key.charCode != 250) //ú
                 && (key.charCode != 193) //Á
                 && (key.charCode != 201) //É
                 && (key.charCode != 205) //Í
                 && (key.charCode != 211) //Ó
                 && (key.charCode != 218) //Ú
                )
                //console.log(key.charCode);
                return false;
	    });
	    /*fin letras*/

	    

	});

 options = {
      "closeButton": true,
      "debug": true,
      "positionClass": "toast-top-right",
      "showDuration": "1000",
      "hideDuration": "1000",
      "timeOut": "5000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    }


/*inicio verificar nombre*/
function verificarNombre(valor)
{
	//alert(valor.length);
	if(valor.length >= 180){
		//alert(valor.length);
		toastr.info("El nombre no puede superar los 180 caracteres", "Ayuda", options);
	}
	return false;
}
/*fin verificar nombre*/

</script>

@endpush

resources/views/enfermedades/edit.blade.php
@extends('master')

@section('title', 'Enfermedades Editar')

@push('css-head')
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="{{asset('assets/plugins/select2/select2_conquer.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{ asset('assets/plugins/bootstrap-toastr/toastr.min.css') }}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/plugins/bootstrap-datepicker/css/datepicker.css')}}"/>


<!-- END PAGE LEVEL STYLES -->
@endpush

@section('content')

@section('content')

<!-- BEGIN CONTENT -->

<div class="page-content-wrapper">
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN PAGE CONTENT-->
			<div class="row">
				<div class="col-md-12">
					<div class="portlet">
						<div class="portlet-title">
							<div class="caption">
								<i class="flaticon-002-first-aid-kit flaticon-med" style="color: black;"></i>Panel de Enfermedades
							</div>
						</div>
						<div class="portlet-body form">
						@if ($errors->any())
							<div class="note note-danger">
								<h6 class="block"><strong>Sigue las siguientes instrucciones :</strong></h6>
								<ul>
						            @foreach ($errors->all() as $error)
						                <li>{{ $error }}</li>
						            @endforeach
						        </ul>
							</div>
						@endif
						<form method="post" class="horizontal-form" id="form_enfermedades" action="{{ route('enfermedades.update',$enfermedad->id) }}">
						{{ method_field('PUT') }}
							<div class="form-body">
								<h3 class="form-section">Editar Enfermedad</h3>
								<div class="row">
									<div class="col-md-8">
										<div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
											<label class="control-label">Nombre (*)</label>
											<input type="text" id="nombre" name="nombre" class="form-control mayusculas" value="{{ $enfermedad->nombre }}" placeholder="Nombre de la Enfermedad" maxlength="180" required onkeyup="verificarNombre(this.value);">
										</div>
									</div>
								</div><!--/row-->
								
								
								
								
								
							</div><!--/div class="form-body"-->
							<div class="form-actions right">
								<a href="{{ asset('enfermedades') }}" title="Cancelar" class="btn btn-default">Cancelar</a>
								<button type="submit" title="Guardar" class="btn btn-info"><i class="fa fa-check"></i> Guardar</button>
							</div>
							{{ csrf_field() }}
						</form>
						</div>
				</div>
			</div>
			<!-- END PAGE CONTENT-->
			
		</div> <!--/div class="page-content" -->
	</div> <!--/div class="page-content-wrapper" -->
</div><!--/div class="page-content-wrapper" -->
<!-- END CONTENT -->
@endsection

@push('script-footer')
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="{{ asset('assets/plugins/select2/select2.min.js') }} "></script>
<script src="{{ asset('assets/plugins/bootstrap-toastr/toastr.min.js') }}"></script>

<script type="text/javascript" src="{{asset('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js')}}"></script>

<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{ asset('assets/scripts/app.js') }} "></script>
<script src="{{ asset('assets/scripts/ui-toastr.js') }}"></script>



<script type="text/javascript">
	$(document).ready(function(){
		App.init(); // initlayout and core plugins
		

   		$("#enfermedades").addClass( "active" );
		$("#enfermedades-li").addClass( "active" );
		$("#enfermedades-a").append( '<span class="selected"></span>' );
		

		/*
	    $("#fecha_nacimiento").change(function(){
            alert($('#fecha_nacimiento').val());
            //$('#valor2').val($(this).val());
		});
		+/

		/*Con esto no se deja ingresar nada que no sea letras*/
	    $(".letras").keypress(function (key) {
            //window.console.log(key.charCode);//imprime el codigo ascii
            if (
                (key.charCode < 97 || key.charCode > 122)//letras mayusculas
                && (key.charCode < 65 || key.charCode > 90) //letras minusculas
                && (key.charCode != 0) //borrar
                && (key.charCode != 32) //espacio
                && (key.charCode != 241) //ñ
                 && (key.charCode != 209) //Ñ
                 && (key.charCode != 225) //á
                 && (key.charCode != 233) //é
                 && (key.charCode != 237) //í
                 && (key.charCode != 243) //ó
                 && (key.charCode != 250) //ú
                 && (key.charCode != 193) //Á
                 && (key.charCode != 201) //É
                 && (key.charCode != 205) //Í
                 && (key.charCode != 211) //Ó
                 && (key.charCode != 218) //Ú
                )
                //console.log(key.charCode);
                return false;
	    });
	    /*fin letras*/

	    

	});

 options = {
      "closeButton": true,
      "debug": true,
      "positionClass": "toast-top-right",
      "showDuration": "1000",
      "hideDuration": "1000",
      "timeOut": "5000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    }


/*inicio verificar nombre*/
function verificarNombre(valor)
{
	//alert(valor.length);
	if(valor.length >= 180){
		//alert(valor.length);
		toastr.info("El nombre no puede superar los 180 caracteres", "Ayuda", options);
	}
	return false;
}
/*fin verificar nombre*/

</script>

@endpush

resources/views/enfermedades/index.blade.php
@extends('master')

@section('title', 'Enfermedades')

@push('css-head')
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="{{asset('assets/plugins/select2/select2_conquer.css')}}"/>
<link rel="stylesheet" href="{{asset('assets/plugins/data-tables/DT_bootstrap.css')}}"/>
<!-- END PAGE LEVEL STYLES -->

@endpush

@section('content')

<!-- BEGIN CONTENT -->

<div class="page-content-wrapper">
	<div class="page-content-wrapper">
		<div class="page-content">

			<!-- BEGIN PAGE CONTENT-->
			<div class="row">
				<div class="col-md-12">
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div class="portlet">
						<div class="portlet-title">
							<div class="caption">
								<i class="flaticon-002-first-aid-kit flaticon-med" style="color: black;"></i>Panel de Enfermedades
							</div>
							<div class="actions">
								<div class="btn-group">
									<a class="btn btn-info dropdown-toggle" href="#" data-toggle="dropdown">
									Columnas <i class="fa fa-angle-down"></i>
									</a>
									<div id="sample_2_column_toggler" class="dropdown-menu hold-on-click dropdown-checkboxes pull-right">
										<label><input type="checkbox" checked data-column="0">Nombre</label>
										<label><input type="checkbox" checked data-column="1">Acción</label>
									</div>
								</div>
							</div>
						</div>
						<div class="portlet-body">
							@if(session("success"))
								@if(Session::get("success")=="add")
									<div class="alert alert-success alert-dismissable">
										<button type="button" title="Cerrar" class="close" data-dismiss="alert" aria-hidden="true"></button>
										<i class="fa fa-thumbs-up fa-flip-horizontal"></i> <strong>Enfermedad creada correctamente!</strong> Tienes {{count($enfermedades)}} enfermedades en el sistema. <u><strong><a class="view-data" data-role="{{session('id_enfermedad')}}" style="cursor: pointer;" >Has click aqui para ver la última enfermedad que creaste</a></strong></u>
									</div>
								@endif
								@if(Session::get("success")=="edit")
									<div class="alert alert-success alert-dismissable">
										<button type="button" title="Cerrar" class="close" data-dismiss="alert" aria-hidden="true"></button>
										<i class="fa fa-thumbs-up fa-flip-horizontal"></i> <strong>Enfermedad editada correctamente!</strong> Tienes {{count($enfermedades)}} enfermedades en el sistema. <u><strong><a class="view-data" data-role="{{session('id_enfermedad')}}" style="cursor: pointer;" >Has click aqui para ver la última enfermedad que editaste</a></strong></u>
									</div>
								@endif
								@if(Session::get("success")=="delete")
									<div class="alert alert-success alert-dismissable">
										<button type="button" title="Cerrar" class="close" data-dismiss="alert" aria-hidden="true"></button>
										<i class="fa fa-thumbs-up fa-flip-horizontal"></i> <strong>Enfermedad eliminada correctamente!</strong> Tienes {{count($enfermedades)}} enfermedades en el sistema.
									</div>
								@endif
							@endif
							<div class="table-toolbar">
								<div class="btn-group">
									@permission('crear_enfermedades')
									<a id="sample_editable_1_new" title="Agregar Nueva enfermedad" href="enfermedades/create" class="btn btn-success">
									Agregar Nueva enfermedad <i class="fa fa-plus"></i>
									</a>
									@endpermission
								</div>
							</div>
							<table class="table table-striped table-bordered table-hover table-full-width" id="sample_2">
								<thead>
								<tr>
									<th>Nombre</th>
									<th class="hidden-xs">Acción</th>
								</tr>
								</thead>
								<tbody>
								@foreach($enfermedades as $enfermedad)
								<tr>
									<td>{{ $enfermedad->nombre }}</td>
									<td>
										<!-- div botones-->
										<div class="clearfix">
											<div class="btn-group">
												@permission('ver_enfermedades')
												<a class="btn btn-default view-data" title="Ver" data-role="{{$enfermedad->id}}" ><i class="fa fa-eye"></i></a>
												@endpermission
												@if($enfermedad->config == 1)
												@permission('editar_enfermedades')
												<a href="{{ url("/enfermedades/$enfermedad->id/edit") }}" title="Editar" class="btn btn-default"><i class="fa fa-edit"></i></a>
												@endpermission
												@permission('eliminar_enfermedades')
												<a class="btn btn-default delete-data" title="Eliminar" data-role="{{$enfermedad->id}}" ><i class="fa fa-trash"></i></a>
												@endpermission
												@endif
											</div>
										</div>
										<!-- /div botones -->
									</td>
								</tr>
								@endforeach
								</tbody>
							</table>
						</div>
					</div>
					<!-- END EXAMPLE TABLE PORTLET-->
				</div>
			</div>
			<!-- END PAGE CONTENT-->
			
			
			
			
		</div> <!--/div class="page-content" -->
	</div> <!--/div class="page-content-wrapper" -->
</div><!--/div class="page-content-wrapper" -->
<!-- END CONTENT -->
<div id="modal"></div>
@endsection

@push('script-footer')
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="{{ asset('assets/plugins/select2/select2.min.js') }} "></script>
<script type="text/javascript" src="{{ asset('assets/plugins/data-tables/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/plugins/data-tables/DT_bootstrap.js') }}"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{ asset('assets/scripts/app.js') }} "></script>
<script src="{{ asset('assets/scripts/table-advanced.js') }} "></script>


<script type="text/javascript">
	$(document).ready(function(){
		App.init(); // initlayout and core plugins
		TableAdvanced.init();

   		$("#enfermedades").addClass( "active" );
		$("#enfermedades-li").addClass( "active" );
		$("#enfermedades-a").append( '<span class="selected"></span>' );

		$(".delete-data").click(function(){
		  var data = $(this).data("role");
		  $.get( "enfermedades/delete/" + data, function( data ) {
			  $( "#modal" ).html( data );
			  $( "#modalEliminar" ).modal();
			});
		});

		$(".view-data").click(function(){
		  var data = $(this).data("role");
		  $.get( "enfermedades/" + data, function( data ) {
			  $( "#modal" ).html( data );
			  $( "#modalVer" ).modal();
			});
		});

	});
</script>

@endpush

resources/views/enfermedades/modaldelete.blade.php
<div id="modalEliminar" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-md" >
        <div class="modal-content">
          <div class="modal-header" style="color: red">
           <i class="fa fa-warning"></i> <strong>  ELIMINAR </strong>
          </div>
          <div class="modal-body">
          	<center>
			<p>¿Está seguro que desea borrar esta enfermedad?</p>
			<p>{{ $enfermedad->nombre }}</p>
			</center>
			<form action="{{ route('enfermedades.destroy',$enfermedad->id) }}" method="post">
				<div class="modal-footer">
					<input type="hidden" name="_token" value="{{ csrf_token() }}">
					<span>
				    	<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					</span>
					<span>
						<button type="submit" title="Confirmar" class="btn btn-info btn-borrar">Confirmar</a>
					</span>
                	{{ method_field('DELETE') }}
				</div>
			</form>
        	</div>
    	</div>
  	</div><!--/modal dialog-->
</div>

resources/views/enfermedades/modalver.blade.php
<div id="modalVer" class="modal fade" tabindex="-1" aria-hidden="false">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header" style="color: rgb(41, 175, 228);">
				<button type="button" title="Cerrar" class="close" data-dismiss="modal" aria-hidden="true"></button>
				<strong>Información de la Enfermedad</strong>
			</div>
			<div class="modal-body">
						<table class="table table-bordered table-hover table-responsive">
						<tbody>
							<tr>
								<th width="25%">Nombre:</th>
								<td width="45%"> {{$enfermedad->nombre}}</td>
							</tr>
						</tbody>
					</table>
					
			</div><!--/modal body-->
			<div class="modal-footer">
				@permission('editar_enfermedades')
				<a href="{{ url("/enfermedades/$enfermedad->id/edit") }}" title="Editar" class="btn btn-warning pull-right"><i class="fa fa-edit"></i> Editar</a>
				@endpermission
			</div>
		</div>
	</div>
</div>