routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*CAMBIAR MAIN POR HOME, para que se vea "mejor"*/
Route::get('/', function () {
    if(Auth::check()){
		return view('/main'); //cambia main por welcome para ver lo de login
	}else{
		return view('auth/login');
	}
});

/*
Route::get('/master', function () {//esto hay que cambiarlo
	if(Auth::check()){
		return view('/main');
	}else{
		return view('auth/login');
	}
    
});
*/
Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/main', 'HomeController@index');

//usuarios
Route::resource('/usuarios','UsersController');
Route::get('/usuarios/delete/{id?}','UsersController@delete');



//pacientes
Route::resource('/pacientes','PacientesController');
Route::get('/pacientes/delete/{id?}','PacientesController@delete');

//enfermedades
Route::resource('/enfermedades','EnfermedadesController');
Route::get('/enfermedades/delete/{id?}','EnfermedadesController@delete');

resources/views/usuarios/index.blade.php
@extends('master')

@section('title', 'Usuarios')

@push('css-head')
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="{{asset('assets/plugins/select2/select2_conquer.css')}}"/>
<link rel="stylesheet" href="{{asset('assets/plugins/data-tables/DT_bootstrap.css')}}"/>
<!-- END PAGE LEVEL STYLES -->
@endpush

@section('content')

<!-- BEGIN CONTENT -->

<div class="page-content-wrapper">
	<div class="page-content-wrapper">
		<div class="page-content">

			<!-- BEGIN PAGE CONTENT-->
			<div class="row">
				<div class="col-md-12">
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div class="portlet">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-users" style="font-size: 23px !important; color: black"></i>Panel de Usuarios
							</div>
							<div class="actions">
								<div class="btn-group">
									<a class="btn btn-info dropdown-toggle" href="#" data-toggle="dropdown">
									Columnas <i class="fa fa-angle-down"></i>
									</a>
									<div id="sample_2_column_toggler" class="dropdown-menu hold-on-click dropdown-checkboxes pull-right">
										<label><input type="checkbox" checked data-column="0">Nombre</label>
										<label><input type="checkbox" checked data-column="1">Correo</label>
										<label><input type="checkbox" checked data-column="2">Rut</label>
										<label><input type="checkbox" checked data-column="3">Tipo</label>
										<label><input type="checkbox" checked data-column="4">Acción</label>
									</div>
								</div>
							</div>
						</div>
						<div class="portlet-body">
							@if(session("success"))
								@if(Session::get("success")=="add")
									<div class="alert alert-success alert-dismissable">
										<button type="button" title="Cerrar" class="close" data-dismiss="alert" aria-hidden="true"></button>
										<i class="fa fa-thumbs-up fa-flip-horizontal"></i> <strong>¡Usuario creado correctamente!</strong> Tienes {{count($usuarios)}} usuarios en el sistema. <u><strong><a class="view-data" data-role="{{session('id_usuario')}}" style="cursor: pointer;" >Has click aqui para ver el último usuario que creaste</a></strong></u>
									</div>
								@endif
								@if(Session::get("success")=="edit")
									<div class="alert alert-success alert-dismissable">
										<button type="button" title="Cerrar" class="close" data-dismiss="alert" aria-hidden="true"></button>
										<i class="fa fa-thumbs-up fa-flip-horizontal"></i> <strong>¡Usuario editado correctamente!</strong> Tienes {{count($usuarios)}} usuarios en el sistema. <u><strong><a class="view-data" data-role="{{session('id_usuario')}}" style="cursor: pointer;" >Has click aqui para ver el último usuario que editaste</a></strong></u>
									</div>
								@endif
								@if(Session::get("success")=="delete")
									<div class="alert alert-success alert-dismissable">
										<button type="button" title="Cerrar" class="close" data-dismiss="alert" aria-hidden="true"></button>
										<i class="fa fa-thumbs-up fa-flip-horizontal"></i> <strong>¡Usuario eliminado correctamente!</strong> Tienes {{count($usuarios)}} usuarios en el sistema.
									</div>
								@endif
							@endif
							<div class="table-toolbar">
								<div class="btn-group">
									@permission('crear_usuarios')
									<a id="sample_editable_1_new" title="Agregar Nuevo Usuario" href="usuarios/create" class="btn btn-success">
									Agregar Nuevo Usuario <i class="fa fa-plus"></i>
									</a>
									@endpermission
								</div>
							</div>
							<table class="table table-striped table-bordered table-hover table-full-width" id="sample_2">
								<thead>
								<tr>
									<th>Nombre</th>
									<th>Correo</th>
									<th class="hidden-xs">Rut</th>
									<th class="hidden-xs">Tipo</th>
									<th class="hidden-xs">Acción</th>
									
								</tr>
								</thead>
								<tbody>
								@foreach($usuarios as $usuario)
								<tr>
									<td>{{ $usuario->nombre." ".$usuario->apellido }}</td>
									<td>{{ $usuario->email }}</td>
									<td>{{ formato_rut($usuario->rut) }}</td>
									<td>{{ $usuario->tipo_usuario->nombre}}</td>
									<td>
										<!-- div botones-->
										<div class="clearfix">
											<div class="btn-group">
												@permission('ver_usuarios')
													<a class="btn btn-default view-data" title="Ver" data-role="{{$usuario->id}}" ><i class="fa fa-eye"></i></a>
												@endpermission
												
												@if($usuario->config == 1 && Auth::user()->id != $usuario->id)
													@permission('editar_usuarios')
														<a href="{{ url("/usuarios/$usuario->id/edit") }}" title="Editar" class="btn btn-default"><i class="fa fa-edit"></i></a>
													@endpermission
													@permission('eliminar_usuarios')
														<a class="btn btn-default delete-data" title="Eliminar" data-role="{{$usuario->id}}" ><i class="fa fa-trash"></i></a>
													@endpermission
												@endif
											</div>
										</div>
										<!-- /div botones -->
									</td>
								</tr>
								@endforeach
								</tbody>
							</table>
						</div>
					</div>
					<!-- END EXAMPLE TABLE PORTLET-->
				</div>
			</div>
			<!-- END PAGE CONTENT-->
			
			
			
			
		</div> <!--/div class="page-content" -->
	</div> <!--/div class="page-content-wrapper" -->
</div><!--/div class="page-content-wrapper" -->
<!-- END CONTENT -->
<div id="modal"></div>
@endsection

@push('script-footer')
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="{{ asset('assets/plugins/select2/select2.min.js') }} "></script>
<script type="text/javascript" src="{{ asset('assets/plugins/data-tables/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/plugins/data-tables/DT_bootstrap.js') }}"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{ asset('assets/scripts/app.js') }} "></script>
<script src="{{ asset('assets/scripts/table-advanced.js') }} "></script>


<script type="text/javascript">
	$(document).ready(function(){
		App.init(); // initlayout and core plugins
		TableAdvanced.init();

   		$("#usuarios").addClass( "active" );
		$("#usuarios-li").addClass( "active" );
		$("#usuarios-a").append( '<span class="selected"></span>' );

		$(".delete-data").click(function(){
		  var data = $(this).data("role");
		  $.get( "usuarios/delete/" + data, function( data ) {
			  $( "#modal" ).html( data );
			  $( "#modalEliminar" ).modal();
			});
		});

		$(".view-data").click(function(){
		  var data = $(this).data("role");
		  $.get( "usuarios/" + data, function( data ) {
			  $( "#modal" ).html( data );
			  $( "#modalVer" ).modal();
			});
		});

	});
</script>

@endpush

resources/views/usuarios/modaldelete.blade.php
<div id="modalEliminar" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-md" >
        <div class="modal-content">
          <div class="modal-header" style="color: red">
           <i class="fa fa-warning"></i> <strong>  ELIMINAR </strong>
          </div>
          <div class="modal-body">
          	<center>
			<p>¿Está seguro que desea borrar este usuario?</p>
			<p>{{ $usuario->nombre ." ". $usuario->apellido }}</p>
			</center>
			<form action="{{ route('usuarios.destroy',$usuario->id) }}" method="post">
				<div class="modal-footer">
					<input type="hidden" name="_token" value="{{ csrf_token() }}">
					<span>
				    	<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					</span>
					<span>
						<button type="submit" title="Confirmar" class="btn btn-info btn-borrar">Confirmar</a>
					</span>
                	{{ method_field('DELETE') }}
				</div>
			</form>
        	</div>
    	</div>
  	</div><!--/modal dialog-->
</div>

resources/views/usuarios/modalver.blade.php
<div id="modalVer" class="modal fade" tabindex="-1" aria-hidden="false">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header" style="color: rgb(41, 175, 228);">
				<button type="button" title="Cerrar" class="close" data-dismiss="modal" aria-hidden="true"></button>
				<strong>Información del Usuario</strong>
			</div>
			<div class="modal-body">
						<table class="table table-bordered table-hover table-responsive">
						<tbody>
							<tr>
								<th width="25%">Nombre:</th>
								<td width="45%"> {{$usuario->nombre}} {{$usuario->apellido}}</td>
							</tr>
								<th >Correo:</th>
								<td >{{$usuario->email}}</td>
							<tr>
							</tr>
							<!--
							<tr>
								<th>Teléfono Fijo:</th>
								<td>{{$usuario->fono}}</td>
								<th>Teléfono Móvil:</th>
								<td>{{$usuario->movil}}</td>
							</tr>
							-->
							<tr>
							</tr>
							<!--
							<tr>
								<th>Departamento:</th>
								<td>{{$usuario->departamento}}</td>
								<th>Cargo:</th>
								<td>{{$usuario->cargo}}</td>
							</tr>
							-->
							<tr>
								<th>Tipo de Usuario:</th>
								<td>{{$usuario->tipo_usuario->nombre}}</td>
							</tr>
							@role(['ADMINISTRADOR','ADMINISTRADOR ODONTÓLOGO'])
							<tr>
								<th>Porcentaje:</th>
								<td>{{ $usuario->porcentaje }} %</td>
							</tr>
							@endrole
							<tr>
								<th>Telefono Contacto :</th>
								<td>{{ $usuario->telefono_contacto }}</td>
							</tr>
						</tbody>
					</table>
					
			</div><!--/modal body-->
			<div class="modal-footer">
				@permission('editar_usuarios')
				<a href="{{ url("/usuarios/$usuario->id/edit") }}" title="Editar" class="btn btn-warning pull-right"><i class="fa fa-edit"></i> Editar</a>
				@endpermission
			</div>
		</div>
	</div>
</div>